version: "3.8"

services:
  # ===================
  # Base de datos
  # ===================
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tingeso
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - mynet

  # ===================
  # BACKEND (3 instancias)
  # ===================
  backend1:
    build:
      context: ./monoliticoBackend
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      KEYCLOAK_ISSUER_URI: http://localhost:8080/realms/toolRent
      REDIRECT_URI: http://localhost:5173*
    depends_on:
      - mysql
      - keycloak
    networks:
      - mynet
    restart: unless-stopped

  backend2:
    build:
      context: ./monoliticoBackend
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      KEYCLOAK_ISSUER_URI: http://localhost:8080/realms/toolRent
      REDIRECT_URI: http://localhost:5173*
    depends_on:
      - mysql
      - keycloak
    networks:
      - mynet
    restart: unless-stopped

  backend3:
    build:
      context: ./monoliticoBackend
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      KEYCLOAK_ISSUER_URI: http://localhost:8080/realms/toolRent
      REDIRECT_URI: http://localhost:5173*
    depends_on:
      - mysql
      - keycloak
    networks:
      - mynet
    restart: unless-stopped

  # ===================
  # FRONTEND
  # ===================
  frontend:
    build:
      context: ./monoliticoFrontend
      dockerfile: Dockerfile
    networks:
      - mynet

  # ===================
  # Nginx para balancear frontend
  # ===================
  nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
        - "5173:80"   # frontend
        - "8090:8090" # backend
      volumes:
        - ./monoliticoFrontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        - ./monoliticoFrontend/dist:/usr/share/nginx/html:ro
      depends_on:
        - frontend
        - backend1
        - backend2
        - backend3
      networks:
        - mynet

  # ===================
  # Keycloak
  # ===================
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.4
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_DATABASE: keycloakdb
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: admin
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"   
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    networks:
      - mynet

# ===================
# Redes
# ===================
networks:
  mynet:
    driver: bridge
